import { poppins } from "@/components/fonts";
import { i18n, Locale } from "@/i18n-config";
import { ThemeProvider } from "@/providers/Theme";
import "@/styles/globals.css";
import type { Metadata, Viewport } from "next";
import { Header } from "@/components/features/site/page/rooms";
import { ClientLayout } from "@/components/layout/container";

export const metadata: Metadata = {
  title: "Hotel Quinto Nivel RD",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

interface LayoutProps {
  children: React.ReactNode;
  params: Promise<{
    lang: Locale;
  }>;
}

export default async function RoomsLayout({ children, params }: LayoutProps) {
  const { lang } = await params;
  return (
    <>
      <ClientLayout lang={lang}>
        <Header lang={lang} />
        {children}
      </ClientLayout>
    </>
  );
}
