import { Header } from "@/components/features/page/rooms";
import { ClientLayout } from "@/components/layout/container";
import { Locale } from "@/i18n-config";
import "@/styles/globals.css";
import { ReactNode } from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hotel Quinto Nivel RD",
  description: "Generated by create next app"
};

interface LayoutProps {
  children: ReactNode;
  params: Promise<{
    lang: Locale;
  }>;
}

export default async function RoomsLayout({ children, params }: LayoutProps) {
  const { lang } = await params;
  return (
    <>
      <ClientLayout lang={lang}>
        <Header lang={lang} />
        {children}
      </ClientLayout>
    </>
  );
}
