import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";

import type { Metadata } from "next";
import { CustomProvider } from "rsuite";
import "../styles/globals.css";
import { poppins } from "../ui/typography";

import enUS from "rsuite/locales/en_US";
import esES from "rsuite/locales/es_ES";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Locale, i18n } from "@/i18n-config";
import { Footer, Navigation } from "../ui/layout/components";
import { HomeHeader } from "../ui/layout/components/Header/Home";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={lang}>
      <body
        className={`${poppins.className} antialiased text-neutral-600 font-sans font-normal min-h-dvh`}
      >
        <CustomProvider
          locale={lang === "en" ? enUS : lang === "es" ? esES : esES}
        >
          <Navigation />
          <header className="h-screen flex items-stretch justify-stretch p-2 header-height">
            <div className="bg-gradient-to-tl from-primary-200 to-neutral-200 flex-1 rounded-md">
              <HomeHeader />
            </div>
          </header>
          {children}
          <Analytics />
          <Footer />
        </CustomProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
