import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import { CustomProvider } from "rsuite";
import "../styles/globals.css";
import { poppins } from "../ui/typography";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Locale, i18n } from "@/i18n-config";
import { Footer, Navigation } from "../ui/layout/components";
import { FrequentlyAskedQuestions } from "../ui/layout/components/Fqa";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={lang}>
      <body className={`${poppins.className} antialiased text-neutral-600`}>
        <CustomProvider>
          <Navigation />
          {children}
          <Footer />
        </CustomProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
