import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

import type { Metadata } from "next";
import { CustomProvider } from "rsuite";
import "../styles/globals.css";
import { poppins } from "../ui/typography";

import enUS from "rsuite/locales/en_US";
import esES from "rsuite/locales/es_ES";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Locale, i18n } from "@/i18n-config";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={lang}>
      <body
        className={`${poppins.className} antialiased text-brand_neutral font-sans font-normal min-h-dvh bg-[#f6f7f9]`}
      >
        <CustomProvider
          locale={lang === "en" ? enUS : lang === "es" ? esES : esES}
        >
          {children}
        </CustomProvider>
      </body>
    </html>
  );
}
