import { Locale } from "@/i18n-config";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Content, Section } from "@/components/layout";
import { Brand } from "@/components/features";
import { ModeToggle } from "@/components/features/site/ModeToggle";
import { Button } from "@/components/ui/button";
import { GoHomeFill } from "@/components/icons";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Hotel Quinto Nivel RD",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
  params: Promise<{
    lang: Locale;
  }>;
}

export default async function AuthLayout({ children, params }: LayoutProps) {
  const { lang } = await params;
  return (
    <Section className="flex min-h-screen w-full items-stretch justify-stretch border border-red-500 p-2 max-[769px]:h-screen min-[769px]:items-center min-[769px]:justify-center">
      <Content className="grid h-full grid-cols-1 gap-4 bg-muted/5 max-[769px]:max-w-[30rem] min-[769px]:grid-cols-[1fr_0.6fr] min-[769px]:p-4 lg:max-w-[80rem]">
        <article className="hidden aspect-[1/1] flex-1 min-[769px]:block">
          <figure className="relative h-full w-full overflow-hidden rounded-br-3xl rounded-tl-3xl">
            <Image
              src="/assets/images/home/header/HQNRD-first-featured-image.webp"
              layout="fill"
              objectFit="cover"
              alt="Auth"
            />
          </figure>
        </article>

        <article className="grid grid-cols-1 grid-rows-[auto_1fr] rounded-bl-3xl rounded-tr-3xl border py-3 max-[769px]:h-full max-[769px]:p-6 min-[769px]:px-6">
          <div className="flex items-center justify-between gap-4">
            <Brand lang={lang} />
            <div className="flex items-center justify-center gap-4">
              <ModeToggle />
              <Link href={`/${lang}`}>
                <Button size="icon" variant="outline">
                  <GoHomeFill />
                </Button>
              </Link>
            </div>
          </div>
          <div className="flex h-full flex-col items-stretch justify-center">
            {children}
          </div>
        </article>
      </Content>
    </Section>
  );
}
