import { poppins } from "@/components/fonts";
import { i18n, Locale } from "@/i18n-config";
import { ThemeProvider } from "@/providers/Theme";
import "@/styles/globals.css";
import type { Metadata, Viewport } from "next";
import { ReactNode } from "react";
import { ScrollArea } from "@/components/ui/scroll-area";
import { ReservationStoreProvider } from "@/providers/ReservationProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { esMX, enUS } from "@clerk/localizations";
import { Profile } from "@/components/features/site/Forms/Profile";
import { headers } from "next/headers";
import { currentUser } from "@clerk/nextjs/server";
import { fetchQuery } from "convex/nextjs";
import { preloadQuery } from "convex/nextjs";
import { api } from "@/convex/_generated/api";

export const metadata: Metadata = {
  title: "Hotel Quinto Nivel RD",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

interface LayoutProps {
  children: ReactNode;
  params: Promise<{
    lang: Locale;
  }>;
}

export default async function RootLayout({ children, params }: LayoutProps) {
  const { lang } = await params;
  const headersList = await headers();
  const defaultCountry = headersList
    .get("accept-language")
    ?.split(",")[0]
    .split("-")[1];

  const user = await currentUser();
  const preloaded = await preloadQuery(api.users.getUser, {
    clerkId: user?.id,
  });

  console.log(preloaded);

  return (
    <ClerkProvider localization={lang == "es" ? esMX : enUS}>
      <html
        lang={lang}
        className={`scroll-smooth focus:scroll-auto ${poppins.className}`}
        suppressHydrationWarning
      >
        <body className={`${poppins.className} subpixel-antialiased`}>
          <ReservationStoreProvider>
            <ScrollArea className="h-[100vh] rounded-md border">
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <>
                  <Profile
                    defaultCountry={defaultCountry}
                    lang={lang}
                    preloaded={preloaded}
                  />
                  {children}
                </>
              </ThemeProvider>
            </ScrollArea>
          </ReservationStoreProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
