import { poppins } from "@/components/fonts";
import { i18n, Locale } from "@/i18n-config";
import { ThemeProvider } from "@/providers/Theme";
import "@/styles/globals.css";
import type { Metadata, Viewport } from "next";
import { ReactNode } from "react";
import { ScrollArea } from "@/components/ui/scroll-area";
import { ReservationStoreProvider } from "@/providers/ReservationProvider";

export const metadata: Metadata = {
  title: "Hotel Quinto Nivel RD",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

interface LayoutProps {
  children: ReactNode;
  params: Promise<{
    lang: Locale;
  }>;
}

export default async function RootLayout({ children, params }: LayoutProps) {
  const { lang } = await params;
  return (
    <html
      lang={lang}
      className={`scroll-smooth focus:scroll-auto ${poppins.className}`}
      suppressHydrationWarning
    >
      <body className={`${poppins.className} subpixel-antialiased`}>
        <ReservationStoreProvider>
          <ScrollArea className="h-[100vh] rounded-md border">
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </ScrollArea>
        </ReservationStoreProvider>
      </body>
    </html>
  );
}
